# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateField(default=datetime.datetime(2016, 12, 9, 3, 13, 35, 275314))),
                ('monto', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='saldo',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprest.User'),
        ),
    ]
