# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 23:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0004_auto_20161209_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='origen',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='destination',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='origin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.DateField(default=datetime.datetime(2016, 12, 9, 23, 52, 24, 863069)),
        ),
    ]
