# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 00:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprest', '0005_auto_20161209_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 10, 0, 21, 16, 649472)),
        ),
    ]
